import { createFileRoute, Link } from "@tanstack/react-router";
import { Building2, Check, X } from "lucide-react";
import { PageHeader, StatCard, Surface } from "@/components/states";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { useMemberSession } from "@/components/layout/use-member";
import { FLAGSHIP, formatBdt } from "@/lib/offers";
import { api, type Booking } from "@/lib/api-client";
import { useAsync } from "@/lib/use-async";
import { formatWhen } from "@/lib/platform";

export const Route=createFileRoute("/app/")({component:OverviewPage});
const primary=(rows:Booking[])=>rows.find(b=>b.status==="activated")||rows.find(b=>b.status==="confirmed")||rows.find(b=>b.status==="pending");

function OverviewPage(){const{user,member}=useMemberSession();const{data:bookings}=useAsync(()=>api.myBookings(),[member?.user_id],{enabled:Boolean(member)});const{data:payments}=useAsync(()=>api.myPayments(),[member?.user_id],{enabled:Boolean(member)});const{data:qual}=useAsync(()=>api.myQualification(),[member?.user_id],{enabled:Boolean(member)});const{data:comm}=useAsync(()=>api.myCommissions(),[member?.user_id],{enabled:Boolean(member)});const{data:tx}=useAsync(()=>api.myTransactions(),[member?.user_id],{enabled:Boolean(member)});if(!member)return null;const booking=primary(bookings?.bookings??[]);const active=member.activation_status==="active";const activationPayment=(payments?.payments??[]).find(p=>p.target_type==="activation");const first=(user?.displayName??"Member").split(" ")[0];return <div className="space-y-8"><PageHeader kicker="Overview" title={`Hello, ${first}`} description="Your property, progress, and financial activity in one place."/>
  {!active?<Surface className="border border-clay/20"><p className="text-xs font-medium uppercase tracking-[.16em] text-clay">Account activation</p><h2 className="mt-3 font-display text-3xl font-semibold">Activate Your Darmelk ID</h2><p className="mt-2 font-display text-2xl">BDT 1,000 <span className="font-sans text-sm text-muted">/ year</span></p><div className="mt-5 flex flex-wrap gap-3"><StatusBadge status={member.activation_status}/>{activationPayment?<StatusBadge status={activationPayment.status}/>:null}</div><p className="mt-4 max-w-xl text-sm leading-relaxed text-muted">Active-member booking, sponsoring, earning, and withdrawal privileges unlock only after payment review and approval.</p><Button asChild className="mt-6"><Link to="/app/activation">Continue Activation</Link></Button></Surface>:
  !booking?<><Surface><p className="text-xs font-medium uppercase tracking-[.16em] text-pine">Darmelk ID</p><h2 className="mt-2 font-display text-3xl font-semibold">Your Darmelk ID is Active</h2><p className="mt-2 text-sm text-muted">Active until {formatWhen(member.activation_expires_at)}.</p></Surface><Surface className="grid gap-5 md:grid-cols-[9rem_1fr_auto] md:items-center"><img src={FLAGSHIP.image} alt={FLAGSHIP.title} className="aspect-[4/3] w-full rounded-xl object-cover md:h-24 md:w-36"/><div><p className="text-xs uppercase tracking-wide text-subtle">Choose your property</p><h2 className="mt-1 font-display text-2xl font-semibold">{FLAGSHIP.title}</h2><p className="mt-1 text-sm text-muted">Initial booking {formatBdt(FLAGSHIP.bookingAmount)}</p></div><Button asChild><Link to="/properties/$slug" params={{slug:FLAGSHIP.slug}}>View Property</Link></Button></Surface><Eligibility ownBooking={false}/></>:
  <><Surface className="grid gap-5 md:grid-cols-[9rem_1fr_auto] md:items-center"><img src={booking.image??FLAGSHIP.image} alt="" className="aspect-[4/3] w-full rounded-xl object-cover md:h-24 md:w-36"/><div><p className="text-xs uppercase tracking-wide text-subtle">Your property</p><h2 className="mt-1 font-display text-2xl font-semibold">{booking.offer_title}</h2><p className="mt-1 text-sm text-muted">Booking {formatBdt(booking.booking_amount)} · Property value {formatBdt(booking.retail_value)} · Benefit {formatBdt(booking.qualification_benefit)}</p></div><div className="space-y-3"><StatusBadge status={booking.status}/><Button asChild size="sm" variant="secondary"><Link to="/app/bookings/$id" params={{id:booking.id}}>Details</Link></Button></div></Surface><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Qualification Progress" value={qual?.qualified?"Qualified":"In Progress"} hint={`${qual?.sponsorCount??0} / 3 personal sponsors`}/><StatCard label="Available Commission" value={formatBdt(comm?.totals.available??0)} hint={`Pending ${formatBdt(comm?.totals.pending??0)}`}/><StatCard label="Booking Status" value={booking.status} hint="Payment and booking history remain recorded."/></div><Eligibility ownBooking={booking.status==="confirmed"||booking.status==="activated"}/><Recent rows={(tx?.transactions??[]).slice(0,4)}/></>}
</div>}

function Eligibility({ownBooking}:{ownBooking:boolean}){return <Surface><h2 className="font-display text-xl font-semibold">Withdrawal Eligibility</h2><ul className="mt-4 space-y-2 text-sm"><li className="flex items-center gap-2"><Check className="size-4 text-pine"/>ID Active</li><li className="flex items-center gap-2">{ownBooking?<Check className="size-4 text-pine"/>:<X className="size-4 text-clay"/>}Own confirmed booking</li></ul>{!ownBooking?<p className="mt-4 text-sm text-muted">Complete your own property booking to unlock withdrawals.</p>:<Button asChild variant="secondary" className="mt-4"><Link to="/app/commission">View earnings</Link></Button>}</Surface>}
function Recent({rows}:{rows:Array<{id:string;type:string;reference:string;amount:number;status:string}>}){return <section><h2 className="font-display text-xl font-semibold">Recent Transactions</h2>{rows.length?<ul className="mt-4 divide-y divide-line rounded-2xl bg-cream">{rows.map(t=><li key={`${t.type}-${t.id}`} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-medium capitalize">{t.type}</p><p className="text-xs text-muted">{t.reference}</p></div><div className="text-right"><p className="text-sm font-semibold">{formatBdt(t.amount)}</p><StatusBadge status={t.status}/></div></li>)}</ul>:<p className="mt-3 text-sm text-muted">No transactions yet.</p>}</section>}
