import { Link } from "@tanstack/react-router";
import * as Accordion from "@radix-ui/react-accordion";
import { ArrowRight, ChevronDown, FileText, Scale, ShieldCheck } from "lucide-react";
import { AmountRow } from "@/components/states";
import { Button } from "@/components/ui/button";
import { FLAGSHIP } from "@/lib/offers";

const steps = [
  ["01", "Create your account", "Create your Darmelk member profile."],
  ["02", "Activate your ID", "Pay the annual BDT 1,000 activation fee and receive approval."],
  ["03", "Choose and book your property", "Review the property, submit payment evidence, and receive booking confirmation."],
  ["04", "Build your progress", "Personally sponsor 3 and progress through five levels to meet qualification conditions."],
];
const faqs = [
  ["What is Darmelk?", "Darmelk is a property-first platform where property terms, bookings, payments, progress, and financial activity are recorded."],
  ["How do I start?", "Create an account, complete your profile, pay the annual BDT 1,000 activation fee, and wait for admin approval before booking."],
  ["What are the qualification conditions?", "Personally sponsor 3 eligible members and complete Level 5. Full details are available in Program Rules."],
  ["Are commission and the property benefit the same?", "No. Commission is calculated from actual eligible confirmed booking amounts. The qualification benefit belongs to your own booked offer."],
];

export function LandingPage() { return <div>
  <section className="relative min-h-[78svh] overflow-hidden bg-ink"><img src={FLAGSHIP.heroImage} alt="Five-Star Hotel Share" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgb(40_33_30/.86),rgb(40_33_30/.28))]"/><div className="container-pg relative flex min-h-[78svh] items-end py-16 pt-28 md:items-center md:py-24"><div className="max-w-2xl text-cream"><p className="text-xs font-medium uppercase tracking-[.2em] text-cream/70">Flagship property</p><h1 className="mt-4 font-display text-4xl font-semibold leading-tight md:text-6xl">Five-Star Hotel Share</h1><div className="mt-7 grid max-w-xl gap-3 sm:grid-cols-3"><HeroFigure label="Property value" value="BDT 650,000"/><HeroFigure label="Initial booking" value="BDT 50,000"/><HeroFigure label="Qualification benefit" value="BDT 600,000"/></div><p className="mt-5 text-sm text-cream/75">Qualification requires 3 personal sponsors and completion through Level 5.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild variant="invert" size="lg"><Link to="/properties/$slug" params={{slug:FLAGSHIP.slug}}>View Property <ArrowRight className="size-4"/></Link></Button><Button asChild variant="invertGhost" size="lg"><a href="#how-it-works">How It Works</a></Button></div></div></div></section>

  <section className="section-y"><div className="container-pg grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><img src={FLAGSHIP.image} alt={FLAGSHIP.title} className="aspect-[16/11] w-full rounded-2xl object-cover"/><div><p className="text-xs font-medium uppercase tracking-[.18em] text-pine">Flagship property</p><h2 className="mt-3 font-display text-3xl font-semibold">{FLAGSHIP.title}</h2><p className="mt-2 text-sm text-muted">{FLAGSHIP.location} · {FLAGSHIP.category}</p><p className="mt-4 text-[15px] leading-relaxed text-muted">{FLAGSHIP.summary}</p><dl className="mt-6 rounded-2xl bg-cream p-5 shadow-[var(--shadow-card)]"><AmountRow label="Property value" value={FLAGSHIP.retailValue}/><AmountRow label="Initial booking" value={FLAGSHIP.bookingAmount}/><AmountRow label="Qualification benefit" value={FLAGSHIP.qualificationBenefit}/></dl><Button asChild className="mt-6"><Link to="/properties/$slug" params={{slug:FLAGSHIP.slug}}>View Details</Link></Button></div></div></section>

  <section id="how-it-works" className="scroll-mt-20 border-y border-line bg-cream section-y"><div className="container-pg"><Heading kicker="Journey" title="How Darmelk works"/><ol className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,title,body])=><li key={n} className="rounded-2xl bg-paper p-6"><p className="font-display text-2xl text-pine">{n}</p><h3 className="mt-3 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{body}</p></li>)}</ol><p className="mt-6 text-center text-sm"><Link to="/program-rules" className="font-medium text-pine hover:underline">See qualification details</Link></p></div></section>

  <section className="section-y"><div className="container-pg"><Heading kicker="Why Darmelk" title="Clear property terms and documented activity"/><div className="mt-10 grid gap-5 md:grid-cols-3"><Trust icon={Scale} title="Clear Property Terms">Offer-specific values and booking conditions are shown before you continue.</Trust><Trust icon={FileText} title="Documented Transactions">Payment, booking, and financial activity remain connected to your member record.</Trust><Trust icon={ShieldCheck} title="Transparent Qualification">Property benefit and commission remain separate and traceable.</Trust></div></div></section>

  <section className="border-y border-line bg-cream section-y"><div className="container-pg grid gap-8 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-pine">Documentation</p><h2 className="mt-3 font-display text-3xl font-semibold">Records connected to your booking</h2><p className="mt-4 leading-relaxed text-muted">Property-related information, booking records, payment evidence, and transaction history are connected to the member’s booking. Sensitive records remain available through the authenticated member area.</p></div><div className="rounded-2xl bg-paper p-6"><p className="font-medium">Before booking</p><p className="mt-2 text-sm text-muted">Review property values, the booking process, payment terms, qualification summary, and applicable program rules.</p><Button asChild variant="secondary" className="mt-5"><Link to="/properties/$slug" params={{slug:FLAGSHIP.slug}}>Review property</Link></Button></div></div></section>

  <section id="faq" className="scroll-mt-20 section-y"><div className="container-pg max-w-3xl"><Heading kicker="FAQ" title="Clear answers before you continue"/><Accordion.Root type="single" collapsible className="mt-9 divide-y divide-line rounded-2xl bg-cream px-5">{faqs.map(([q,a],i)=><Accordion.Item value={`q-${i}`} key={q}><Accordion.Header><Accordion.Trigger className="flex w-full items-center justify-between gap-4 py-5 text-left font-medium">{q}<ChevronDown className="size-4 shrink-0"/></Accordion.Trigger></Accordion.Header><Accordion.Content className="pb-5 text-sm leading-relaxed text-muted">{a}</Accordion.Content></Accordion.Item>)}</Accordion.Root><p className="mt-5 text-center text-sm"><Link to="/faq" className="font-medium text-pine hover:underline">View full FAQ and program mechanics</Link></p></div></section>

  <section className="bg-pine py-14 text-pine-fg"><div className="container-pg flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-3xl font-semibold">Explore the property</h2><p className="mt-2 text-sm text-pine-fg/75">Review the offer and create your account when you are ready.</p></div><div className="flex gap-3"><Button asChild variant="invert"><Link to="/properties/$slug" params={{slug:FLAGSHIP.slug}}>View Property</Link></Button><Button asChild variant="invertGhost"><Link to="/login" search={{mode:"create"}}>Create Account</Link></Button></div></div></section>
</div> }

function HeroFigure({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-cream/20 bg-ink/25 p-3 backdrop-blur-sm"><p className="text-[11px] uppercase tracking-wide text-cream/60">{label}</p><p className="mt-1 whitespace-nowrap font-display text-lg font-semibold">{value}</p></div>}
function Heading({kicker,title}:{kicker:string;title:string}){return <div className="text-center"><p className="text-xs font-medium uppercase tracking-[.18em] text-pine">{kicker}</p><h2 className="mt-3 font-display text-3xl font-semibold md:text-4xl">{title}</h2></div>}
function Trust({icon:Icon,title,children}:{icon:typeof Scale;title:string;children:React.ReactNode}){return <article className="rounded-2xl bg-cream p-6"><Icon className="size-5 text-pine"/><h3 className="mt-4 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{children}</p></article>}
