// Commission postings: 10% / 8% / 6% / 4% / 2% for matrix levels 1-5,
// computed from the SOURCE member's actual confirmed booking amount — never
// a hard-coded platform-wide figure, so mixed offers (different booking
// amounts) each pay commission on their own real amount.
import type { PoolClient } from "pg";
import { uid } from "../ids.js";
import { getMatrixAncestors } from "./network.js";

export const COMMISSION_RATES: Record<number, number> = {
  1: 0.1,
  2: 0.08,
  3: 0.06,
  4: 0.04,
  5: 0.02,
};

export type PostedCommission = {
  id: string;
  beneficiaryUserId: string;
  level: number;
  amount: number;
};

/**
 * Post commission ledger rows for every matrix ancestor of the booking's
 * owner, one row per level, amount = round(booking_amount * rate).
 *
 * Idempotent: `commission_ledger` has a unique constraint on
 * (source_booking_id, beneficiary_user_id, level), and this uses
 * `ON CONFLICT DO NOTHING` — safe to call again for the same booking (e.g. a
 * retried admin confirmation) without double-crediting anyone. Must run
 * inside the SAME transaction as the booking status update that triggers it.
 */
export async function postCommissionsForBooking(
  client: PoolClient,
  booking: { id: string; userId: string; bookingAmount: number },
): Promise<PostedCommission[]> {
  const ancestors = await getMatrixAncestors(client, booking.userId);
  const posted: PostedCommission[] = [];

  for (const { userId: beneficiaryUserId, level } of ancestors) {
    const rate = COMMISSION_RATES[level];
    if (!rate) continue;
    const amount = Math.round(booking.bookingAmount * rate);
    const id = uid("cm");
    const { rowCount } = await client.query(
      `insert into commission_ledger
         (id, beneficiary_user_id, source_booking_id, source_user_id, level, rate, source_booking_amount, amount, status)
       values ($1, $2, $3, $4, $5, $6, $7, $8, 'available')
       on conflict (source_booking_id, beneficiary_user_id, level) do nothing`,
      [id, beneficiaryUserId, booking.id, booking.userId, level, rate, booking.bookingAmount, amount],
    );
    if (rowCount) posted.push({ id, beneficiaryUserId, level, amount });
  }
  return posted;
}

/**
 * Reverse every commission_ledger row generated by a booking: flips each to
 * 'reversed' and writes one reversal_entries row per commission — the
 * original row and its amount are never touched, only appended-to.
 */
export async function reverseCommissionsForBooking(
  client: PoolClient,
  bookingId: string,
  opts: { reason: string; adminUserId: string },
): Promise<number> {
  const { rows } = await client.query<{ id: string; amount: number }>(
    `select id, amount from commission_ledger
      where source_booking_id = $1 and status not in ('reversed', 'rejected')
      for update`,
    [bookingId],
  );
  for (const row of rows) {
    await client.query(
      `insert into reversal_entries (id, commission_ledger_id, reversed_amount, reason, reversed_by_admin_id)
       values ($1, $2, $3, $4, $5)`,
      [uid("rv"), row.id, row.amount, opts.reason, opts.adminUserId],
    );
    await client.query(`update commission_ledger set status = 'reversed', updated_at = now() where id = $1`, [
      row.id,
    ]);
  }
  return rows.length;
}

export async function getCommissionTotals(
  client: PoolClient,
  userId: string,
): Promise<{ available: number; pending: number; paid: number; reversed: number; rejected: number }> {
  const { rows } = await client.query<{ status: string; total: string }>(
    `select status, coalesce(sum(amount), 0)::text as total
       from commission_ledger where beneficiary_user_id = $1 group by status`,
    [userId],
  );
  const totals = { available: 0, pending: 0, paid: 0, reversed: 0, rejected: 0 };
  for (const r of rows) {
    if (r.status in totals) (totals as Record<string, number>)[r.status] = Number(r.total);
  }
  return totals;
}
