import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(root, rel), "utf8");

test("promotion qualification stays on the single confirmBooking path", () => {
  const engine = read("backend/src/engine/promotions.ts");
  const bookings = read("backend/src/engine/bookings.ts");
  const merchant = read("backend/src/engine/merchant.ts");
  const activation = read("backend/src/engine/activation.ts");
  const payments = read("backend/src/engine/payments.ts");
  const contact = read("backend/src/engine/contact.ts");
  const router = read("backend/src/router.ts");
  assert.match(engine, /evaluatePromotionsForConfirmedBooking/);
  assert.match(engine, /Channel-neutral/);
  assert.match(engine, /on conflict \(promotion_id, user_id\) do nothing/);
  assert.match(engine, /promotionTermsVersion: POLICY_DOCUMENTS\.PROMOTION_TERMS\.version/);
  assert.match(bookings, /evaluatePromotionsForConfirmedBooking/);
  assert.match(bookings, /Single qualification entry for every payment rail/);
  assert.match(bookings, /consumeInventoryForConfirmation/);
  assert.doesNotMatch(engine, /payment_method/);
  assert.doesNotMatch(engine, /requireCurrentConsents/);
  assert.doesNotMatch(engine, /recordConsents/);
  assert.doesNotMatch(engine, /Mark User Qualified/);
  assert.doesNotMatch(merchant, /evaluatePromotionsForConfirmedBooking/);
  assert.doesNotMatch(activation, /evaluatePromotionsForConfirmedBooking/);
  assert.doesNotMatch(payments, /evaluatePromotionsForConfirmedBooking/);
  assert.doesNotMatch(contact, /evaluatePromotionsForConfirmedBooking/);
  const approve = merchant.slice(merchant.indexOf("export async function approveMerchantPaymentRequest"));
  assert.doesNotMatch(approve.slice(0, 2500), /confirmBooking|activateBooking|consumeInventoryForConfirmation|evaluatePromotions/);
  const paymentDecision = router.slice(router.indexOf('app.post("/api/admin/payments/:id/:decision"'));
  assert.match(paymentDecision, /await confirmBooking\(client, result.target_id, adminId\)/);
  assert.match(paymentDecision, /await activateBooking\(client, result.target_id\)/);
  assert.doesNotMatch(router, /evaluatePromotionsForConfirmedBooking/);
  assert.doesNotMatch(router, /Mark User Qualified/);
  assert.doesNotMatch(router, /\/api\/admin\/promotions\/qualify/);
});

test("Promotion Terms are readable, versioned, and not a blocking consent gate", () => {
  const terms = read("backend/src/engine/terms.ts");
  const router = read("backend/src/router.ts");
  const activation = read("backend/src/engine/activation.ts");
  const merchant = read("backend/src/engine/merchant.ts");
  const bookings = read("backend/src/engine/bookings.ts");
  const promoBlock = terms.slice(terms.indexOf("PROMOTION_TERMS:"), terms.indexOf("const KEY_SET"));
  assert.match(promoBlock, /key: "PROMOTION_TERMS"/);
  assert.match(promoBlock, /version: "1"/);
  assert.match(promoBlock, /slug: "promotion"/);
  assert.match(promoBlock, /campaign-specific/);
  assert.match(promoBlock, /Darmelk Bank bookings and Pay by Merchant bookings/);
  assert.match(promoBlock, /Merchant approval, payment submission/);
  assert.match(promoBlock, /Request to Book/);
  assert.match(promoBlock, /does not generate commission/);
  assert.match(promoBlock, /does not guarantee a promotion reward/);
  assert.match(promoBlock, /LEGAL_NOTE/);
  assert.doesNotMatch(promoBlock, /guaranteed gift/i);
  assert.doesNotMatch(promoBlock, /Link Mate/);
  assert.doesNotMatch(promoBlock, /11,000|11000/);
  assert.match(router, /app\.get\("\/api\/terms\/:key"/);
  assert.match(router, /recordConsents\(client, userId, \{[\s\S]*GENERAL_TERMS[\s\S]*PRIVACY_POLICY/);
  assert.doesNotMatch(router, /recordConsents\([\s\S]*PROMOTION_TERMS/);
  assert.doesNotMatch(activation, /PROMOTION_TERMS/);
  assert.doesNotMatch(merchant, /PROMOTION_TERMS/);
  assert.doesNotMatch(bookings, /PROMOTION_TERMS/);
  assert.match(bookings, /PROPERTY_BOOKING_TERMS/);
});

test("promotion UI wires readable Terms without changing the dashboard grid", () => {
  const dashboard = read("src/components/promotions/dashboard-promotions.tsx");
  const index = read("src/routes/app/promotions.index.tsx");
  const detail = read("src/routes/app/promotions.$id.tsx");
  assert.match(dashboard, /md:grid-cols-\[minmax\(0,1\.65fr\)_minmax\(14\.5rem,0\.92fr\)\]/);
  assert.match(dashboard, /Current promotion/);
  assert.match(dashboard, /Time remaining/);
  assert.match(dashboard, /View details/);
  assert.match(dashboard, /More promotions/);
  assert.match(dashboard, /search=\{\{\s*key:\s*"promotion"\s*\}\}/);
  assert.match(dashboard, /Promotion Terms/);
  assert.match(index, /Darmelk Bank and Pay by Merchant/);
  assert.match(index, /Request to Book is not enough/);
  assert.match(index, /search=\{\{\s*key:\s*"promotion"\s*\}\}/);
  assert.match(detail, /Not Yet Qualified/);
  assert.match(detail, /Reward Fulfilled/);
  assert.match(detail, /Darmelk Bank and Pay by Merchant bookings qualify the/);
  assert.match(detail, /Read Promotion Terms/);
  assert.match(detail, /Campaign terms/);
  assert.match(detail, /search=\{\{\s*key:\s*"promotion"\s*\}\}/);
  assert.match(detail, /does not\s+guarantee a gift/);
  assert.doesNotMatch(dashboard, /guaranteed gift/i);
  assert.doesNotMatch(index, /guaranteed gift/i);
  assert.doesNotMatch(detail, /guaranteed gift/i);
  assert.doesNotMatch(dashboard, /Mark User Qualified/);
  assert.doesNotMatch(detail, /Mark User Qualified/);
});

test("Batch 05 and 06 rails stay untouched and no new migration is added", () => {
  const form = read("src/components/payment-form.tsx");
  const book = read("src/routes/app/book.$slug.tsx");
  const payments = read("backend/src/engine/payments.ts");
  const activation = read("backend/src/engine/activation.ts");
  const commissions = read("backend/src/engine/commissions.ts");
  const network = read("backend/src/engine/network.ts");
  const leadership = read("backend/src/engine/leadership.ts");
  const inventory = read("backend/src/engine/inventory.ts");
  const smoke = read("backend/src/smoke-test.ts");
  assert.match(form, /allowMerchant = targetType === "booking"/);
  assert.match(book, /Pay via Darmelk Bank or Pay by Merchant/);
  assert.match(payments, /targetType === "booking" && method !== "bank"/);
  assert.match(activation, /1000/);
  assert.doesNotMatch(activation, /payment_method_not_allowed/);
  assert.match(commissions, /1: 0\.1/);
  assert.match(network, /PERSONAL_SPONSOR_TARGET = 3/);
  assert.match(leadership, /TIER_25K = 25_000/);
  assert.match(inventory, /consumeInventoryForConfirmation/);
  assert.match(smoke, /Growth Bank booking pending does not qualify/);
  assert.match(smoke, /Growth Bank payment submission does not qualify/);
  assert.match(smoke, /Growth Bank payment approval qualifies through existing confirmation/);
  assert.match(smoke, /Merchant approval alone does not qualify for a promotion/);
  assert.match(smoke, /Merchant-funded booking qualifies only after existing confirmation/);
  assert.match(smoke, /Merchant approval does not consume inventory/);
  assert.match(smoke, /Contact and Request to Book do not qualify for a promotion/);
  assert.match(smoke, /Promotion Terms are readable without consent/);
  const files = readdirSync(join(root, "migrations")).filter((name) => name.endsWith(".sql") && name.startsWith("001"));
  assert.ok(files.includes("0016_darmelk_promotion.sql"));
  assert.ok(files.includes("0019_darmelk_consents.sql"));
  assert.equal(files.filter((name) => name.startsWith("002")).length, 0);
});
