/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRulesRouteImport } from './routes/program-rules'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivationRouteImport } from './routes/admin/activation'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminCareerRouteImport } from './routes/admin/career'
import { Route as AdminCommissionRouteImport } from './routes/admin/commission'
import { Route as AdminContactRequestsRouteImport } from './routes/admin/contact-requests'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminLeadershipRewardsRouteImport } from './routes/admin/leadership-rewards'
import { Route as AdminMerchantRouteImport } from './routes/admin/merchant'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivationRouteImport } from './routes/app/activation'
import { Route as AppBookingsRouteImport } from './routes/app/bookings'
import { Route as AppCommissionRouteImport } from './routes/app/commission'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppLeadershipRewardRouteImport } from './routes/app/leadership-reward'
import { Route as AppMerchantRouteImport } from './routes/app/merchant'
import { Route as AppNetworkRouteImport } from './routes/app/network'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppQualificationRouteImport } from './routes/app/qualification'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as CareerIndexRouteImport } from './routes/career/index'
import { Route as CareerSlugRouteImport } from './routes/career.$slug'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as AdminCareerIndexRouteImport } from './routes/admin/career.index'
import { Route as AdminCareerSlugRouteImport } from './routes/admin/career.$slug'
import { Route as AdminCareerNewRouteImport } from './routes/admin/career.new'
import { Route as AdminLeadershipRewardsIndexRouteImport } from './routes/admin/leadership-rewards.index'
import { Route as AdminLeadershipRewardsUserIdRouteImport } from './routes/admin/leadership-rewards.$userId'
import { Route as AdminMerchantIndexRouteImport } from './routes/admin/merchant.index'
import { Route as AdminMerchantAccountsRouteImport } from './routes/admin/merchant.accounts'
import { Route as AdminMerchantBundlesRouteImport } from './routes/admin/merchant.bundles'
import { Route as AdminMerchantGiftsRouteImport } from './routes/admin/merchant.gifts'
import { Route as AdminMerchantLedgerRouteImport } from './routes/admin/merchant.ledger'
import { Route as AdminMerchantRequestsRouteImport } from './routes/admin/merchant.requests'
import { Route as AdminOffersIndexRouteImport } from './routes/admin/offers.index'
import { Route as AdminOffersSlugRouteImport } from './routes/admin/offers.$slug'
import { Route as AdminOffersNewRouteImport } from './routes/admin/offers.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppBookSlugRouteImport } from './routes/app/book.$slug'
import { Route as AppBookingsIdRouteImport } from './routes/app/bookings.$id'
import { Route as AdminCareerSlugIndexRouteImport } from './routes/admin/career.$slug.index'
import { Route as AdminCareerSlugPreviewRouteImport } from './routes/admin/career.$slug.preview'
import { Route as AdminMerchantAccountsIndexRouteImport } from './routes/admin/merchant.accounts.index'
import { Route as AdminMerchantAccountsUserIdRouteImport } from './routes/admin/merchant.accounts.$userId'
import { Route as AdminMerchantBundlesIndexRouteImport } from './routes/admin/merchant.bundles.index'
import { Route as AdminMerchantBundlesIdRouteImport } from './routes/admin/merchant.bundles.$id'
import { Route as AdminMerchantBundlesNewRouteImport } from './routes/admin/merchant.bundles.new'
import { Route as AdminOffersSlugIndexRouteImport } from './routes/admin/offers.$slug.index'
import { Route as AdminOffersSlugPreviewRouteImport } from './routes/admin/offers.$slug.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRulesRoute = ProgramRulesRouteImport.update({
  id: '/program-rules',
  path: '/program-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivationRoute = AdminActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerRoute = AdminCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionRoute = AdminCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRequestsRoute = AdminContactRequestsRouteImport.update({
  id: '/contact-requests',
  path: '/contact-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadershipRewardsRoute = AdminLeadershipRewardsRouteImport.update({
  id: '/leadership-rewards',
  path: '/leadership-rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantRoute = AdminMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationRoute = AppActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionRoute = AppCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadershipRewardRoute = AppLeadershipRewardRouteImport.update({
  id: '/leadership-reward',
  path: '/leadership-reward',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantRoute = AppMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationRoute = AppQualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const CareerSlugRoute = CareerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareerRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const AdminCareerIndexRoute = AdminCareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCareerRoute,
} as any)
const AdminCareerSlugRoute = AdminCareerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCareerRoute,
} as any)
const AdminCareerNewRoute = AdminCareerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCareerRoute,
} as any)
const AdminLeadershipRewardsIndexRoute =
  AdminLeadershipRewardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLeadershipRewardsRoute,
  } as any)
const AdminLeadershipRewardsUserIdRoute =
  AdminLeadershipRewardsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminLeadershipRewardsRoute,
  } as any)
const AdminMerchantIndexRoute = AdminMerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminMerchantAccountsRoute = AdminMerchantAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminMerchantBundlesRoute = AdminMerchantBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminMerchantGiftsRoute = AdminMerchantGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminMerchantLedgerRoute = AdminMerchantLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminMerchantRequestsRoute = AdminMerchantRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminMerchantRoute,
} as any)
const AdminOffersIndexRoute = AdminOffersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOffersRoute,
} as any)
const AdminOffersSlugRoute = AdminOffersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminOffersRoute,
} as any)
const AdminOffersNewRoute = AdminOffersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOffersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookSlugRoute = AppBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBookingsRoute,
} as any)
const AdminCareerSlugIndexRoute = AdminCareerSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCareerSlugRoute,
} as any)
const AdminCareerSlugPreviewRoute = AdminCareerSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminCareerSlugRoute,
} as any)
const AdminMerchantAccountsIndexRoute =
  AdminMerchantAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMerchantAccountsRoute,
  } as any)
const AdminMerchantAccountsUserIdRoute =
  AdminMerchantAccountsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminMerchantAccountsRoute,
  } as any)
const AdminMerchantBundlesIndexRoute =
  AdminMerchantBundlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMerchantBundlesRoute,
  } as any)
const AdminMerchantBundlesIdRoute = AdminMerchantBundlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMerchantBundlesRoute,
} as any)
const AdminMerchantBundlesNewRoute = AdminMerchantBundlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMerchantBundlesRoute,
} as any)
const AdminOffersSlugIndexRoute = AdminOffersSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOffersSlugRoute,
} as any)
const AdminOffersSlugPreviewRoute = AdminOffersSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminOffersSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/career': typeof AdminCareerRouteWithChildren
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leadership-rewards': typeof AdminLeadershipRewardsRouteWithChildren
  '/admin/merchant': typeof AdminMerchantRouteWithChildren
  '/admin/network': typeof AdminNetworkRoute
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/leadership-reward': typeof AppLeadershipRewardRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/career/$slug': typeof CareerSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/career/': typeof CareerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/career/$slug': typeof AdminCareerSlugRouteWithChildren
  '/admin/career/new': typeof AdminCareerNewRoute
  '/admin/leadership-rewards/$userId': typeof AdminLeadershipRewardsUserIdRoute
  '/admin/merchant/accounts': typeof AdminMerchantAccountsRouteWithChildren
  '/admin/merchant/bundles': typeof AdminMerchantBundlesRouteWithChildren
  '/admin/merchant/gifts': typeof AdminMerchantGiftsRoute
  '/admin/merchant/ledger': typeof AdminMerchantLedgerRoute
  '/admin/merchant/requests': typeof AdminMerchantRequestsRoute
  '/admin/offers/$slug': typeof AdminOffersSlugRouteWithChildren
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/admin/career/': typeof AdminCareerIndexRoute
  '/admin/leadership-rewards/': typeof AdminLeadershipRewardsIndexRoute
  '/admin/merchant/': typeof AdminMerchantIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/career/$slug/preview': typeof AdminCareerSlugPreviewRoute
  '/admin/merchant/accounts/$userId': typeof AdminMerchantAccountsUserIdRoute
  '/admin/merchant/bundles/$id': typeof AdminMerchantBundlesIdRoute
  '/admin/merchant/bundles/new': typeof AdminMerchantBundlesNewRoute
  '/admin/offers/$slug/preview': typeof AdminOffersSlugPreviewRoute
  '/admin/career/$slug/': typeof AdminCareerSlugIndexRoute
  '/admin/merchant/accounts/': typeof AdminMerchantAccountsIndexRoute
  '/admin/merchant/bundles/': typeof AdminMerchantBundlesIndexRoute
  '/admin/offers/$slug/': typeof AdminOffersSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/leadership-reward': typeof AppLeadershipRewardRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/career/$slug': typeof CareerSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/career': typeof CareerIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/career/new': typeof AdminCareerNewRoute
  '/admin/leadership-rewards/$userId': typeof AdminLeadershipRewardsUserIdRoute
  '/admin/merchant/gifts': typeof AdminMerchantGiftsRoute
  '/admin/merchant/ledger': typeof AdminMerchantLedgerRoute
  '/admin/merchant/requests': typeof AdminMerchantRequestsRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/admin/career': typeof AdminCareerIndexRoute
  '/admin/leadership-rewards': typeof AdminLeadershipRewardsIndexRoute
  '/admin/merchant': typeof AdminMerchantIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/career/$slug/preview': typeof AdminCareerSlugPreviewRoute
  '/admin/merchant/accounts/$userId': typeof AdminMerchantAccountsUserIdRoute
  '/admin/merchant/bundles/$id': typeof AdminMerchantBundlesIdRoute
  '/admin/merchant/bundles/new': typeof AdminMerchantBundlesNewRoute
  '/admin/offers/$slug/preview': typeof AdminOffersSlugPreviewRoute
  '/admin/career/$slug': typeof AdminCareerSlugIndexRoute
  '/admin/merchant/accounts': typeof AdminMerchantAccountsIndexRoute
  '/admin/merchant/bundles': typeof AdminMerchantBundlesIndexRoute
  '/admin/offers/$slug': typeof AdminOffersSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/career': typeof AdminCareerRouteWithChildren
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leadership-rewards': typeof AdminLeadershipRewardsRouteWithChildren
  '/admin/merchant': typeof AdminMerchantRouteWithChildren
  '/admin/network': typeof AdminNetworkRoute
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/leadership-reward': typeof AppLeadershipRewardRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/career/$slug': typeof CareerSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/career/': typeof CareerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/career/$slug': typeof AdminCareerSlugRouteWithChildren
  '/admin/career/new': typeof AdminCareerNewRoute
  '/admin/leadership-rewards/$userId': typeof AdminLeadershipRewardsUserIdRoute
  '/admin/merchant/accounts': typeof AdminMerchantAccountsRouteWithChildren
  '/admin/merchant/bundles': typeof AdminMerchantBundlesRouteWithChildren
  '/admin/merchant/gifts': typeof AdminMerchantGiftsRoute
  '/admin/merchant/ledger': typeof AdminMerchantLedgerRoute
  '/admin/merchant/requests': typeof AdminMerchantRequestsRoute
  '/admin/offers/$slug': typeof AdminOffersSlugRouteWithChildren
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/admin/career/': typeof AdminCareerIndexRoute
  '/admin/leadership-rewards/': typeof AdminLeadershipRewardsIndexRoute
  '/admin/merchant/': typeof AdminMerchantIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/career/$slug/preview': typeof AdminCareerSlugPreviewRoute
  '/admin/merchant/accounts/$userId': typeof AdminMerchantAccountsUserIdRoute
  '/admin/merchant/bundles/$id': typeof AdminMerchantBundlesIdRoute
  '/admin/merchant/bundles/new': typeof AdminMerchantBundlesNewRoute
  '/admin/offers/$slug/preview': typeof AdminOffersSlugPreviewRoute
  '/admin/career/$slug/': typeof AdminCareerSlugIndexRoute
  '/admin/merchant/accounts/': typeof AdminMerchantAccountsIndexRoute
  '/admin/merchant/bundles/': typeof AdminMerchantBundlesIndexRoute
  '/admin/offers/$slug/': typeof AdminOffersSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/career'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/properties'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/career'
    | '/admin/commission'
    | '/admin/contact-requests'
    | '/admin/documents'
    | '/admin/leadership-rewards'
    | '/admin/merchant'
    | '/admin/network'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/leadership-reward'
    | '/app/merchant'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/career/$slug'
    | '/properties/$slug'
    | '/admin/'
    | '/app/'
    | '/career/'
    | '/properties/'
    | '/admin/career/$slug'
    | '/admin/career/new'
    | '/admin/leadership-rewards/$userId'
    | '/admin/merchant/accounts'
    | '/admin/merchant/bundles'
    | '/admin/merchant/gifts'
    | '/admin/merchant/ledger'
    | '/admin/merchant/requests'
    | '/admin/offers/$slug'
    | '/admin/offers/new'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
    | '/admin/career/'
    | '/admin/leadership-rewards/'
    | '/admin/merchant/'
    | '/admin/offers/'
    | '/admin/career/$slug/preview'
    | '/admin/merchant/accounts/$userId'
    | '/admin/merchant/bundles/$id'
    | '/admin/merchant/bundles/new'
    | '/admin/offers/$slug/preview'
    | '/admin/career/$slug/'
    | '/admin/merchant/accounts/'
    | '/admin/merchant/bundles/'
    | '/admin/offers/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/commission'
    | '/admin/contact-requests'
    | '/admin/documents'
    | '/admin/network'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/leadership-reward'
    | '/app/merchant'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/career/$slug'
    | '/properties/$slug'
    | '/admin'
    | '/app'
    | '/career'
    | '/properties'
    | '/admin/career/new'
    | '/admin/leadership-rewards/$userId'
    | '/admin/merchant/gifts'
    | '/admin/merchant/ledger'
    | '/admin/merchant/requests'
    | '/admin/offers/new'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
    | '/admin/career'
    | '/admin/leadership-rewards'
    | '/admin/merchant'
    | '/admin/offers'
    | '/admin/career/$slug/preview'
    | '/admin/merchant/accounts/$userId'
    | '/admin/merchant/bundles/$id'
    | '/admin/merchant/bundles/new'
    | '/admin/offers/$slug/preview'
    | '/admin/career/$slug'
    | '/admin/merchant/accounts'
    | '/admin/merchant/bundles'
    | '/admin/offers/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/career'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/properties'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/career'
    | '/admin/commission'
    | '/admin/contact-requests'
    | '/admin/documents'
    | '/admin/leadership-rewards'
    | '/admin/merchant'
    | '/admin/network'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/leadership-reward'
    | '/app/merchant'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/career/$slug'
    | '/properties/$slug'
    | '/admin/'
    | '/app/'
    | '/career/'
    | '/properties/'
    | '/admin/career/$slug'
    | '/admin/career/new'
    | '/admin/leadership-rewards/$userId'
    | '/admin/merchant/accounts'
    | '/admin/merchant/bundles'
    | '/admin/merchant/gifts'
    | '/admin/merchant/ledger'
    | '/admin/merchant/requests'
    | '/admin/offers/$slug'
    | '/admin/offers/new'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
    | '/admin/career/'
    | '/admin/leadership-rewards/'
    | '/admin/merchant/'
    | '/admin/offers/'
    | '/admin/career/$slug/preview'
    | '/admin/merchant/accounts/$userId'
    | '/admin/merchant/bundles/$id'
    | '/admin/merchant/bundles/new'
    | '/admin/offers/$slug/preview'
    | '/admin/career/$slug/'
    | '/admin/merchant/accounts/'
    | '/admin/merchant/bundles/'
    | '/admin/offers/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CareerRoute: typeof CareerRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRulesRoute: typeof ProgramRulesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-rules': {
      id: '/program-rules'
      path: '/program-rules'
      fullPath: '/program-rules'
      preLoaderRoute: typeof ProgramRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activation': {
      id: '/admin/activation'
      path: '/activation'
      fullPath: '/admin/activation'
      preLoaderRoute: typeof AdminActivationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career': {
      id: '/admin/career'
      path: '/career'
      fullPath: '/admin/career'
      preLoaderRoute: typeof AdminCareerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commission': {
      id: '/admin/commission'
      path: '/commission'
      fullPath: '/admin/commission'
      preLoaderRoute: typeof AdminCommissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-requests': {
      id: '/admin/contact-requests'
      path: '/contact-requests'
      fullPath: '/admin/contact-requests'
      preLoaderRoute: typeof AdminContactRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leadership-rewards': {
      id: '/admin/leadership-rewards'
      path: '/leadership-rewards'
      fullPath: '/admin/leadership-rewards'
      preLoaderRoute: typeof AdminLeadershipRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchant': {
      id: '/admin/merchant'
      path: '/merchant'
      fullPath: '/admin/merchant'
      preLoaderRoute: typeof AdminMerchantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation': {
      id: '/app/activation'
      path: '/activation'
      fullPath: '/app/activation'
      preLoaderRoute: typeof AppActivationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commission': {
      id: '/app/commission'
      path: '/commission'
      fullPath: '/app/commission'
      preLoaderRoute: typeof AppCommissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leadership-reward': {
      id: '/app/leadership-reward'
      path: '/leadership-reward'
      fullPath: '/app/leadership-reward'
      preLoaderRoute: typeof AppLeadershipRewardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/merchant': {
      id: '/app/merchant'
      path: '/merchant'
      fullPath: '/app/merchant'
      preLoaderRoute: typeof AppMerchantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qualification': {
      id: '/app/qualification'
      path: '/qualification'
      fullPath: '/app/qualification'
      preLoaderRoute: typeof AppQualificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/$slug': {
      id: '/career/$slug'
      path: '/$slug'
      fullPath: '/career/$slug'
      preLoaderRoute: typeof CareerSlugRouteImport
      parentRoute: typeof CareerRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/admin/career/': {
      id: '/admin/career/'
      path: '/'
      fullPath: '/admin/career/'
      preLoaderRoute: typeof AdminCareerIndexRouteImport
      parentRoute: typeof AdminCareerRoute
    }
    '/admin/career/$slug': {
      id: '/admin/career/$slug'
      path: '/$slug'
      fullPath: '/admin/career/$slug'
      preLoaderRoute: typeof AdminCareerSlugRouteImport
      parentRoute: typeof AdminCareerRoute
    }
    '/admin/career/new': {
      id: '/admin/career/new'
      path: '/new'
      fullPath: '/admin/career/new'
      preLoaderRoute: typeof AdminCareerNewRouteImport
      parentRoute: typeof AdminCareerRoute
    }
    '/admin/leadership-rewards/': {
      id: '/admin/leadership-rewards/'
      path: '/'
      fullPath: '/admin/leadership-rewards/'
      preLoaderRoute: typeof AdminLeadershipRewardsIndexRouteImport
      parentRoute: typeof AdminLeadershipRewardsRoute
    }
    '/admin/leadership-rewards/$userId': {
      id: '/admin/leadership-rewards/$userId'
      path: '/$userId'
      fullPath: '/admin/leadership-rewards/$userId'
      preLoaderRoute: typeof AdminLeadershipRewardsUserIdRouteImport
      parentRoute: typeof AdminLeadershipRewardsRoute
    }
    '/admin/merchant/': {
      id: '/admin/merchant/'
      path: '/'
      fullPath: '/admin/merchant/'
      preLoaderRoute: typeof AdminMerchantIndexRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/merchant/accounts': {
      id: '/admin/merchant/accounts'
      path: '/accounts'
      fullPath: '/admin/merchant/accounts'
      preLoaderRoute: typeof AdminMerchantAccountsRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/merchant/bundles': {
      id: '/admin/merchant/bundles'
      path: '/bundles'
      fullPath: '/admin/merchant/bundles'
      preLoaderRoute: typeof AdminMerchantBundlesRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/merchant/gifts': {
      id: '/admin/merchant/gifts'
      path: '/gifts'
      fullPath: '/admin/merchant/gifts'
      preLoaderRoute: typeof AdminMerchantGiftsRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/merchant/ledger': {
      id: '/admin/merchant/ledger'
      path: '/ledger'
      fullPath: '/admin/merchant/ledger'
      preLoaderRoute: typeof AdminMerchantLedgerRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/merchant/requests': {
      id: '/admin/merchant/requests'
      path: '/requests'
      fullPath: '/admin/merchant/requests'
      preLoaderRoute: typeof AdminMerchantRequestsRouteImport
      parentRoute: typeof AdminMerchantRoute
    }
    '/admin/offers/': {
      id: '/admin/offers/'
      path: '/'
      fullPath: '/admin/offers/'
      preLoaderRoute: typeof AdminOffersIndexRouteImport
      parentRoute: typeof AdminOffersRoute
    }
    '/admin/offers/$slug': {
      id: '/admin/offers/$slug'
      path: '/$slug'
      fullPath: '/admin/offers/$slug'
      preLoaderRoute: typeof AdminOffersSlugRouteImport
      parentRoute: typeof AdminOffersRoute
    }
    '/admin/offers/new': {
      id: '/admin/offers/new'
      path: '/new'
      fullPath: '/admin/offers/new'
      preLoaderRoute: typeof AdminOffersNewRouteImport
      parentRoute: typeof AdminOffersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book/$slug': {
      id: '/app/book/$slug'
      path: '/book/$slug'
      fullPath: '/app/book/$slug'
      preLoaderRoute: typeof AppBookSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$id': {
      id: '/app/bookings/$id'
      path: '/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppBookingsRoute
    }
    '/admin/career/$slug/': {
      id: '/admin/career/$slug/'
      path: '/'
      fullPath: '/admin/career/$slug/'
      preLoaderRoute: typeof AdminCareerSlugIndexRouteImport
      parentRoute: typeof AdminCareerSlugRoute
    }
    '/admin/career/$slug/preview': {
      id: '/admin/career/$slug/preview'
      path: '/preview'
      fullPath: '/admin/career/$slug/preview'
      preLoaderRoute: typeof AdminCareerSlugPreviewRouteImport
      parentRoute: typeof AdminCareerSlugRoute
    }
    '/admin/merchant/accounts/': {
      id: '/admin/merchant/accounts/'
      path: '/'
      fullPath: '/admin/merchant/accounts/'
      preLoaderRoute: typeof AdminMerchantAccountsIndexRouteImport
      parentRoute: typeof AdminMerchantAccountsRoute
    }
    '/admin/merchant/accounts/$userId': {
      id: '/admin/merchant/accounts/$userId'
      path: '/$userId'
      fullPath: '/admin/merchant/accounts/$userId'
      preLoaderRoute: typeof AdminMerchantAccountsUserIdRouteImport
      parentRoute: typeof AdminMerchantAccountsRoute
    }
    '/admin/merchant/bundles/': {
      id: '/admin/merchant/bundles/'
      path: '/'
      fullPath: '/admin/merchant/bundles/'
      preLoaderRoute: typeof AdminMerchantBundlesIndexRouteImport
      parentRoute: typeof AdminMerchantBundlesRoute
    }
    '/admin/merchant/bundles/$id': {
      id: '/admin/merchant/bundles/$id'
      path: '/$id'
      fullPath: '/admin/merchant/bundles/$id'
      preLoaderRoute: typeof AdminMerchantBundlesIdRouteImport
      parentRoute: typeof AdminMerchantBundlesRoute
    }
    '/admin/merchant/bundles/new': {
      id: '/admin/merchant/bundles/new'
      path: '/new'
      fullPath: '/admin/merchant/bundles/new'
      preLoaderRoute: typeof AdminMerchantBundlesNewRouteImport
      parentRoute: typeof AdminMerchantBundlesRoute
    }
    '/admin/offers/$slug/': {
      id: '/admin/offers/$slug/'
      path: '/'
      fullPath: '/admin/offers/$slug/'
      preLoaderRoute: typeof AdminOffersSlugIndexRouteImport
      parentRoute: typeof AdminOffersSlugRoute
    }
    '/admin/offers/$slug/preview': {
      id: '/admin/offers/$slug/preview'
      path: '/preview'
      fullPath: '/admin/offers/$slug/preview'
      preLoaderRoute: typeof AdminOffersSlugPreviewRouteImport
      parentRoute: typeof AdminOffersSlugRoute
    }
  }
}

interface AdminCareerSlugRouteChildren {
  AdminCareerSlugPreviewRoute: typeof AdminCareerSlugPreviewRoute
  AdminCareerSlugIndexRoute: typeof AdminCareerSlugIndexRoute
}

const AdminCareerSlugRouteChildren: AdminCareerSlugRouteChildren = {
  AdminCareerSlugPreviewRoute: AdminCareerSlugPreviewRoute,
  AdminCareerSlugIndexRoute: AdminCareerSlugIndexRoute,
}

const AdminCareerSlugRouteWithChildren = AdminCareerSlugRoute._addFileChildren(
  AdminCareerSlugRouteChildren,
)

interface AdminCareerRouteChildren {
  AdminCareerSlugRoute: typeof AdminCareerSlugRouteWithChildren
  AdminCareerNewRoute: typeof AdminCareerNewRoute
  AdminCareerIndexRoute: typeof AdminCareerIndexRoute
}

const AdminCareerRouteChildren: AdminCareerRouteChildren = {
  AdminCareerSlugRoute: AdminCareerSlugRouteWithChildren,
  AdminCareerNewRoute: AdminCareerNewRoute,
  AdminCareerIndexRoute: AdminCareerIndexRoute,
}

const AdminCareerRouteWithChildren = AdminCareerRoute._addFileChildren(
  AdminCareerRouteChildren,
)

interface AdminLeadershipRewardsRouteChildren {
  AdminLeadershipRewardsUserIdRoute: typeof AdminLeadershipRewardsUserIdRoute
  AdminLeadershipRewardsIndexRoute: typeof AdminLeadershipRewardsIndexRoute
}

const AdminLeadershipRewardsRouteChildren: AdminLeadershipRewardsRouteChildren =
  {
    AdminLeadershipRewardsUserIdRoute: AdminLeadershipRewardsUserIdRoute,
    AdminLeadershipRewardsIndexRoute: AdminLeadershipRewardsIndexRoute,
  }

const AdminLeadershipRewardsRouteWithChildren =
  AdminLeadershipRewardsRoute._addFileChildren(
    AdminLeadershipRewardsRouteChildren,
  )

interface AdminMerchantAccountsRouteChildren {
  AdminMerchantAccountsUserIdRoute: typeof AdminMerchantAccountsUserIdRoute
  AdminMerchantAccountsIndexRoute: typeof AdminMerchantAccountsIndexRoute
}

const AdminMerchantAccountsRouteChildren: AdminMerchantAccountsRouteChildren = {
  AdminMerchantAccountsUserIdRoute: AdminMerchantAccountsUserIdRoute,
  AdminMerchantAccountsIndexRoute: AdminMerchantAccountsIndexRoute,
}

const AdminMerchantAccountsRouteWithChildren =
  AdminMerchantAccountsRoute._addFileChildren(
    AdminMerchantAccountsRouteChildren,
  )

interface AdminMerchantBundlesRouteChildren {
  AdminMerchantBundlesIdRoute: typeof AdminMerchantBundlesIdRoute
  AdminMerchantBundlesNewRoute: typeof AdminMerchantBundlesNewRoute
  AdminMerchantBundlesIndexRoute: typeof AdminMerchantBundlesIndexRoute
}

const AdminMerchantBundlesRouteChildren: AdminMerchantBundlesRouteChildren = {
  AdminMerchantBundlesIdRoute: AdminMerchantBundlesIdRoute,
  AdminMerchantBundlesNewRoute: AdminMerchantBundlesNewRoute,
  AdminMerchantBundlesIndexRoute: AdminMerchantBundlesIndexRoute,
}

const AdminMerchantBundlesRouteWithChildren =
  AdminMerchantBundlesRoute._addFileChildren(AdminMerchantBundlesRouteChildren)

interface AdminMerchantRouteChildren {
  AdminMerchantAccountsRoute: typeof AdminMerchantAccountsRouteWithChildren
  AdminMerchantBundlesRoute: typeof AdminMerchantBundlesRouteWithChildren
  AdminMerchantGiftsRoute: typeof AdminMerchantGiftsRoute
  AdminMerchantLedgerRoute: typeof AdminMerchantLedgerRoute
  AdminMerchantRequestsRoute: typeof AdminMerchantRequestsRoute
  AdminMerchantIndexRoute: typeof AdminMerchantIndexRoute
}

const AdminMerchantRouteChildren: AdminMerchantRouteChildren = {
  AdminMerchantAccountsRoute: AdminMerchantAccountsRouteWithChildren,
  AdminMerchantBundlesRoute: AdminMerchantBundlesRouteWithChildren,
  AdminMerchantGiftsRoute: AdminMerchantGiftsRoute,
  AdminMerchantLedgerRoute: AdminMerchantLedgerRoute,
  AdminMerchantRequestsRoute: AdminMerchantRequestsRoute,
  AdminMerchantIndexRoute: AdminMerchantIndexRoute,
}

const AdminMerchantRouteWithChildren = AdminMerchantRoute._addFileChildren(
  AdminMerchantRouteChildren,
)

interface AdminOffersSlugRouteChildren {
  AdminOffersSlugPreviewRoute: typeof AdminOffersSlugPreviewRoute
  AdminOffersSlugIndexRoute: typeof AdminOffersSlugIndexRoute
}

const AdminOffersSlugRouteChildren: AdminOffersSlugRouteChildren = {
  AdminOffersSlugPreviewRoute: AdminOffersSlugPreviewRoute,
  AdminOffersSlugIndexRoute: AdminOffersSlugIndexRoute,
}

const AdminOffersSlugRouteWithChildren = AdminOffersSlugRoute._addFileChildren(
  AdminOffersSlugRouteChildren,
)

interface AdminOffersRouteChildren {
  AdminOffersSlugRoute: typeof AdminOffersSlugRouteWithChildren
  AdminOffersNewRoute: typeof AdminOffersNewRoute
  AdminOffersIndexRoute: typeof AdminOffersIndexRoute
}

const AdminOffersRouteChildren: AdminOffersRouteChildren = {
  AdminOffersSlugRoute: AdminOffersSlugRouteWithChildren,
  AdminOffersNewRoute: AdminOffersNewRoute,
  AdminOffersIndexRoute: AdminOffersIndexRoute,
}

const AdminOffersRouteWithChildren = AdminOffersRoute._addFileChildren(
  AdminOffersRouteChildren,
)

interface AdminRouteChildren {
  AdminActivationRoute: typeof AdminActivationRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCareerRoute: typeof AdminCareerRouteWithChildren
  AdminCommissionRoute: typeof AdminCommissionRoute
  AdminContactRequestsRoute: typeof AdminContactRequestsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLeadershipRewardsRoute: typeof AdminLeadershipRewardsRouteWithChildren
  AdminMerchantRoute: typeof AdminMerchantRouteWithChildren
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminOffersRoute: typeof AdminOffersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivationRoute: AdminActivationRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCareerRoute: AdminCareerRouteWithChildren,
  AdminCommissionRoute: AdminCommissionRoute,
  AdminContactRequestsRoute: AdminContactRequestsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLeadershipRewardsRoute: AdminLeadershipRewardsRouteWithChildren,
  AdminMerchantRoute: AdminMerchantRouteWithChildren,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminOffersRoute: AdminOffersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppBookingsRouteChildren {
  AppBookingsIdRoute: typeof AppBookingsIdRoute
}

const AppBookingsRouteChildren: AppBookingsRouteChildren = {
  AppBookingsIdRoute: AppBookingsIdRoute,
}

const AppBookingsRouteWithChildren = AppBookingsRoute._addFileChildren(
  AppBookingsRouteChildren,
)

interface AppRouteChildren {
  AppActivationRoute: typeof AppActivationRoute
  AppBookingsRoute: typeof AppBookingsRouteWithChildren
  AppCommissionRoute: typeof AppCommissionRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppLeadershipRewardRoute: typeof AppLeadershipRewardRoute
  AppMerchantRoute: typeof AppMerchantRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppQualificationRoute: typeof AppQualificationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookSlugRoute: typeof AppBookSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivationRoute: AppActivationRoute,
  AppBookingsRoute: AppBookingsRouteWithChildren,
  AppCommissionRoute: AppCommissionRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppLeadershipRewardRoute: AppLeadershipRewardRoute,
  AppMerchantRoute: AppMerchantRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppQualificationRoute: AppQualificationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookSlugRoute: AppBookSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CareerRouteChildren {
  CareerSlugRoute: typeof CareerSlugRoute
  CareerIndexRoute: typeof CareerIndexRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerSlugRoute: CareerSlugRoute,
  CareerIndexRoute: CareerIndexRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CareerRoute: CareerRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRulesRoute: ProgramRulesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
