/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRulesRouteImport } from './routes/program-rules'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivationRouteImport } from './routes/admin/activation'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminCommissionRouteImport } from './routes/admin/commission'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivationRouteImport } from './routes/app/activation'
import { Route as AppBookingsRouteImport } from './routes/app/bookings'
import { Route as AppCommissionRouteImport } from './routes/app/commission'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppNetworkRouteImport } from './routes/app/network'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppQualificationRouteImport } from './routes/app/qualification'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppBookSlugRouteImport } from './routes/app/book.$slug'
import { Route as AppBookingsIdRouteImport } from './routes/app/bookings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRulesRoute = ProgramRulesRouteImport.update({
  id: '/program-rules',
  path: '/program-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivationRoute = AdminActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionRoute = AdminCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationRoute = AppActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionRoute = AppCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationRoute = AppQualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookSlugRoute = AppBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/program-rules': typeof ProgramRulesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/activation': typeof AdminActivationRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/activation': typeof AppActivationRoute
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/commission': typeof AppCommissionRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/network': typeof AppNetworkRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/qualification': typeof AppQualificationRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/book/$slug': typeof AppBookSlugRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/properties'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/commission'
    | '/admin/documents'
    | '/admin/network'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/properties/$slug'
    | '/admin/'
    | '/app/'
    | '/properties/'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/commission'
    | '/admin/documents'
    | '/admin/network'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/properties/$slug'
    | '/admin'
    | '/app'
    | '/properties'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/program-rules'
    | '/properties'
    | '/reset-password'
    | '/terms'
    | '/admin/activation'
    | '/admin/bookings'
    | '/admin/commission'
    | '/admin/documents'
    | '/admin/network'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/activation'
    | '/app/bookings'
    | '/app/commission'
    | '/app/documents'
    | '/app/network'
    | '/app/onboarding'
    | '/app/qualification'
    | '/app/settings'
    | '/app/transactions'
    | '/properties/$slug'
    | '/admin/'
    | '/app/'
    | '/properties/'
    | '/api/auth/$'
    | '/app/book/$slug'
    | '/app/bookings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRulesRoute: typeof ProgramRulesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-rules': {
      id: '/program-rules'
      path: '/program-rules'
      fullPath: '/program-rules'
      preLoaderRoute: typeof ProgramRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activation': {
      id: '/admin/activation'
      path: '/activation'
      fullPath: '/admin/activation'
      preLoaderRoute: typeof AdminActivationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commission': {
      id: '/admin/commission'
      path: '/commission'
      fullPath: '/admin/commission'
      preLoaderRoute: typeof AdminCommissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation': {
      id: '/app/activation'
      path: '/activation'
      fullPath: '/app/activation'
      preLoaderRoute: typeof AppActivationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commission': {
      id: '/app/commission'
      path: '/commission'
      fullPath: '/app/commission'
      preLoaderRoute: typeof AppCommissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qualification': {
      id: '/app/qualification'
      path: '/qualification'
      fullPath: '/app/qualification'
      preLoaderRoute: typeof AppQualificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book/$slug': {
      id: '/app/book/$slug'
      path: '/book/$slug'
      fullPath: '/app/book/$slug'
      preLoaderRoute: typeof AppBookSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$id': {
      id: '/app/bookings/$id'
      path: '/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppBookingsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivationRoute: typeof AdminActivationRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCommissionRoute: typeof AdminCommissionRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivationRoute: AdminActivationRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCommissionRoute: AdminCommissionRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppBookingsRouteChildren {
  AppBookingsIdRoute: typeof AppBookingsIdRoute
}

const AppBookingsRouteChildren: AppBookingsRouteChildren = {
  AppBookingsIdRoute: AppBookingsIdRoute,
}

const AppBookingsRouteWithChildren = AppBookingsRoute._addFileChildren(
  AppBookingsRouteChildren,
)

interface AppRouteChildren {
  AppActivationRoute: typeof AppActivationRoute
  AppBookingsRoute: typeof AppBookingsRouteWithChildren
  AppCommissionRoute: typeof AppCommissionRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppQualificationRoute: typeof AppQualificationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookSlugRoute: typeof AppBookSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivationRoute: AppActivationRoute,
  AppBookingsRoute: AppBookingsRouteWithChildren,
  AppCommissionRoute: AppCommissionRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppQualificationRoute: AppQualificationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookSlugRoute: AppBookSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRulesRoute: ProgramRulesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
